server:
  context-path: /sell

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: springboot
    password: SpringBoot@123
    url: jdbc:mysql://192.168.1.116/springboot?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null